import type { GitHubRepo } from "@/types";

export const DEMO_USERNAME = "demo";

export const DEMO_REPOS: GitHubRepo[] = [
  // AI & Machine Learning
  {
    id: 1,
    name: "ollama",
    full_name: "ollama/ollama",
    description:
      "Get up and running with Llama 3, Mistral, Gemma, and other large language models.",
    html_url: "https://github.com/ollama/ollama",
    stargazers_count: 128000,
    language: "Go",
    topics: ["llm", "ai", "machine-learning", "llama", "mistral"],
    owner: { login: "ollama", avatar_url: "https://avatars.githubusercontent.com/u/127165244" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 2,
    name: "langchain",
    full_name: "langchain-ai/langchain",
    description: "Build context-aware reasoning applications",
    html_url: "https://github.com/langchain-ai/langchain",
    stargazers_count: 98000,
    language: "Python",
    topics: ["llm", "ai", "langchain", "gpt", "openai"],
    owner: {
      login: "langchain-ai",
      avatar_url: "https://avatars.githubusercontent.com/u/126733545",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 3,
    name: "stable-diffusion-webui",
    full_name: "AUTOMATIC1111/stable-diffusion-webui",
    description: "Stable Diffusion web UI",
    html_url: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    stargazers_count: 145000,
    language: "Python",
    topics: ["stable-diffusion", "ai", "image-generation", "deep-learning"],
    owner: {
      login: "AUTOMATIC1111",
      avatar_url: "https://avatars.githubusercontent.com/u/20920490",
    },
    updated_at: "2024-11-15T00:00:00Z",
    fork: false,
    private: false,
  },

  // UI Components
  {
    id: 10,
    name: "ui",
    full_name: "shadcn-ui/ui",
    description: "Beautifully designed components that you can copy and paste into your apps.",
    html_url: "https://github.com/shadcn-ui/ui",
    stargazers_count: 78000,
    language: "TypeScript",
    topics: ["ui", "components", "react", "tailwindcss", "radix-ui"],
    owner: { login: "shadcn-ui", avatar_url: "https://avatars.githubusercontent.com/u/139895814" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 11,
    name: "radix-ui",
    full_name: "radix-ui/primitives",
    description:
      "Radix Primitives is an open-source UI component library for building accessible web apps.",
    html_url: "https://github.com/radix-ui/primitives",
    stargazers_count: 16500,
    language: "TypeScript",
    topics: ["ui", "components", "react", "accessibility", "headless-ui"],
    owner: { login: "radix-ui", avatar_url: "https://avatars.githubusercontent.com/u/75042455" },
    updated_at: "2024-11-20T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 12,
    name: "aceternity-ui",
    full_name: "aceternity/aceternity-ui",
    description: "Copy paste the most trending components and use them in your websites.",
    html_url: "https://github.com/aceternity/aceternity-ui",
    stargazers_count: 4200,
    language: "TypeScript",
    topics: ["ui", "components", "react", "tailwindcss", "framer-motion"],
    owner: { login: "aceternity", avatar_url: "https://avatars.githubusercontent.com/u/143517202" },
    updated_at: "2024-11-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Developer Tools
  {
    id: 20,
    name: "lazygit",
    full_name: "jesseduffield/lazygit",
    description: "simple terminal UI for git commands",
    html_url: "https://github.com/jesseduffield/lazygit",
    stargazers_count: 54000,
    language: "Go",
    topics: ["git", "cli", "terminal", "developer-tools"],
    owner: {
      login: "jesseduffield",
      avatar_url: "https://avatars.githubusercontent.com/u/8456633",
    },
    updated_at: "2024-11-28T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 21,
    name: "starship",
    full_name: "starship/starship",
    description: "The minimal, blazing-fast, and infinitely customizable prompt for any shell!",
    html_url: "https://github.com/starship/starship",
    stargazers_count: 47000,
    language: "Rust",
    topics: ["cli", "shell", "terminal", "prompt", "developer-tools"],
    owner: { login: "starship", avatar_url: "https://avatars.githubusercontent.com/u/79409258" },
    updated_at: "2024-11-25T00:00:00Z",
    fork: false,
    private: false,
  },

  // Runtime & Build Tools
  {
    id: 30,
    name: "bun",
    full_name: "oven-sh/bun",
    description: "Incredibly fast JavaScript runtime, bundler, test runner, and package manager.",
    html_url: "https://github.com/oven-sh/bun",
    stargazers_count: 75000,
    language: "Zig",
    topics: ["javascript", "runtime", "bundler", "typescript", "package-manager"],
    owner: { login: "oven-sh", avatar_url: "https://avatars.githubusercontent.com/u/108928776" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 31,
    name: "vite",
    full_name: "vitejs/vite",
    description: "Next generation frontend tooling. It's fast!",
    html_url: "https://github.com/vitejs/vite",
    stargazers_count: 70000,
    language: "TypeScript",
    topics: ["bundler", "build-tool", "frontend", "vite", "esm"],
    owner: { login: "vitejs", avatar_url: "https://avatars.githubusercontent.com/u/65625612" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 32,
    name: "esbuild",
    full_name: "evanw/esbuild",
    description: "An extremely fast bundler for the web",
    html_url: "https://github.com/evanw/esbuild",
    stargazers_count: 38500,
    language: "Go",
    topics: ["bundler", "javascript", "typescript", "build-tool"],
    owner: { login: "evanw", avatar_url: "https://avatars.githubusercontent.com/u/406130" },
    updated_at: "2024-11-20T00:00:00Z",
    fork: false,
    private: false,
  },

  // APIs & Backend
  {
    id: 40,
    name: "hono",
    full_name: "honojs/hono",
    description: "Web framework built on Web Standards",
    html_url: "https://github.com/honojs/hono",
    stargazers_count: 22000,
    language: "TypeScript",
    topics: ["api", "backend", "web-framework", "cloudflare-workers", "bun"],
    owner: { login: "honojs", avatar_url: "https://avatars.githubusercontent.com/u/98495527" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 41,
    name: "trpc",
    full_name: "trpc/trpc",
    description: "Move Fast and Break Nothing. End-to-end typesafe APIs made easy.",
    html_url: "https://github.com/trpc/trpc",
    stargazers_count: 36000,
    language: "TypeScript",
    topics: ["api", "typescript", "trpc", "graphql-alternative", "backend"],
    owner: { login: "trpc", avatar_url: "https://avatars.githubusercontent.com/u/78011399" },
    updated_at: "2024-11-28T00:00:00Z",
    fork: false,
    private: false,
  },

  // Data & Visualization
  {
    id: 50,
    name: "recharts",
    full_name: "recharts/recharts",
    description: "Redefined chart library built with React and D3",
    html_url: "https://github.com/recharts/recharts",
    stargazers_count: 24500,
    language: "TypeScript",
    topics: ["charts", "react", "d3", "data-visualization", "charting"],
    owner: { login: "recharts", avatar_url: "https://avatars.githubusercontent.com/u/13525856" },
    updated_at: "2024-11-15T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 51,
    name: "d3",
    full_name: "d3/d3",
    description: "Bring data to life with SVG, Canvas and HTML.",
    html_url: "https://github.com/d3/d3",
    stargazers_count: 109000,
    language: "JavaScript",
    topics: ["data-visualization", "charts", "svg", "d3js"],
    owner: { login: "d3", avatar_url: "https://avatars.githubusercontent.com/u/1562726" },
    updated_at: "2024-10-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Documentation
  {
    id: 60,
    name: "awesome-selfhosted",
    full_name: "awesome-selfhosted/awesome-selfhosted",
    description: "A list of Free Software network services and web applications.",
    html_url: "https://github.com/awesome-selfhosted/awesome-selfhosted",
    stargazers_count: 210000,
    language: null,
    topics: ["awesome-list", "selfhosted", "documentation"],
    owner: {
      login: "awesome-selfhosted",
      avatar_url: "https://avatars.githubusercontent.com/u/54384355",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 61,
    name: "free-programming-books",
    full_name: "EbookFoundation/free-programming-books",
    description: "Freely available programming books",
    html_url: "https://github.com/EbookFoundation/free-programming-books",
    stargazers_count: 345000,
    language: null,
    topics: ["awesome-list", "documentation", "books", "learning"],
    owner: {
      login: "EbookFoundation",
      avatar_url: "https://avatars.githubusercontent.com/u/14127529",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 62,
    name: "developer-roadmap",
    full_name: "kamranahmedse/developer-roadmap",
    description: "Interactive roadmaps, guides and other educational content.",
    html_url: "https://github.com/kamranahmedse/developer-roadmap",
    stargazers_count: 305000,
    language: "TypeScript",
    topics: ["documentation", "learning", "roadmap", "guides"],
    owner: {
      login: "kamranahmedse",
      avatar_url: "https://avatars.githubusercontent.com/u/4921183",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Database
  {
    id: 70,
    name: "drizzle-orm",
    full_name: "drizzle-team/drizzle-orm",
    description: "Headless TypeScript ORM with a head.",
    html_url: "https://github.com/drizzle-team/drizzle-orm",
    stargazers_count: 26000,
    language: "TypeScript",
    topics: ["database", "orm", "typescript", "sql", "postgresql"],
    owner: {
      login: "drizzle-team",
      avatar_url: "https://avatars.githubusercontent.com/u/108468352",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 71,
    name: "prisma",
    full_name: "prisma/prisma",
    description: "Next-generation ORM for Node.js & TypeScript",
    html_url: "https://github.com/prisma/prisma",
    stargazers_count: 40500,
    language: "TypeScript",
    topics: ["database", "orm", "typescript", "postgresql", "mysql"],
    owner: { login: "prisma", avatar_url: "https://avatars.githubusercontent.com/u/17219288" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Security
  {
    id: 80,
    name: "lucia",
    full_name: "lucia-auth/lucia",
    description: "Authentication, simple and clean",
    html_url: "https://github.com/lucia-auth/lucia",
    stargazers_count: 10500,
    language: "TypeScript",
    topics: ["authentication", "auth", "security", "session"],
    owner: { login: "lucia-auth", avatar_url: "https://avatars.githubusercontent.com/u/118108822" },
    updated_at: "2024-11-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // State Management
  {
    id: 90,
    name: "zustand",
    full_name: "pmndrs/zustand",
    description: "Bear necessities for state management in React",
    html_url: "https://github.com/pmndrs/zustand",
    stargazers_count: 49500,
    language: "TypeScript",
    topics: ["state-management", "react", "zustand", "state"],
    owner: { login: "pmndrs", avatar_url: "https://avatars.githubusercontent.com/u/45790596" },
    updated_at: "2024-11-20T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 91,
    name: "jotai",
    full_name: "pmndrs/jotai",
    description: "Primitive and flexible state management for React",
    html_url: "https://github.com/pmndrs/jotai",
    stargazers_count: 19500,
    language: "TypeScript",
    topics: ["state-management", "react", "jotai", "atoms"],
    owner: { login: "pmndrs", avatar_url: "https://avatars.githubusercontent.com/u/45790596" },
    updated_at: "2024-11-15T00:00:00Z",
    fork: false,
    private: false,
  },

  // Analytics & Monitoring
  {
    id: 100,
    name: "posthog",
    full_name: "PostHog/posthog",
    description: "Open source product analytics, session recording, feature flags and A/B testing.",
    html_url: "https://github.com/PostHog/posthog",
    stargazers_count: 23500,
    language: "Python",
    topics: ["analytics", "product-analytics", "monitoring", "observability"],
    owner: { login: "PostHog", avatar_url: "https://avatars.githubusercontent.com/u/60330232" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 101,
    name: "plausible",
    full_name: "plausible/analytics",
    description: "Simple, open source, lightweight and privacy-friendly web analytics.",
    html_url: "https://github.com/plausible/analytics",
    stargazers_count: 21500,
    language: "Elixir",
    topics: ["analytics", "web-analytics", "privacy", "monitoring"],
    owner: { login: "plausible", avatar_url: "https://avatars.githubusercontent.com/u/54802774" },
    updated_at: "2024-11-28T00:00:00Z",
    fork: false,
    private: false,
  },

  // Utilities
  {
    id: 110,
    name: "excalidraw",
    full_name: "excalidraw/excalidraw",
    description: "Virtual whiteboard for sketching hand-drawn like diagrams",
    html_url: "https://github.com/excalidraw/excalidraw",
    stargazers_count: 90000,
    language: "TypeScript",
    topics: ["whiteboard", "drawing", "utility", "collaboration"],
    owner: { login: "excalidraw", avatar_url: "https://avatars.githubusercontent.com/u/59452120" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 111,
    name: "pdf.js",
    full_name: "mozilla/pdf.js",
    description: "PDF Reader in JavaScript",
    html_url: "https://github.com/mozilla/pdf.js",
    stargazers_count: 49500,
    language: "JavaScript",
    topics: ["pdf", "javascript", "viewer", "utility"],
    owner: { login: "mozilla", avatar_url: "https://avatars.githubusercontent.com/u/131524" },
    updated_at: "2024-11-25T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 112,
    name: "starcorn",
    full_name: "nathan-abela/starcorn",
    description: "Organize, filter, and export GitHub stars. Fully client-side.",
    html_url: "https://github.com/nathan-abela/starcorn",
    stargazers_count: 6,
    language: "TypeScript",
    topics: ["github", "stars", "organizer", "utility", "export"],
    owner: {
      login: "nathan-abela",
      avatar_url: "https://avatars.githubusercontent.com/u/50643013",
    },
    updated_at: "2026-06-28T00:00:00Z",
    fork: false,
    private: false,
  },

  // Design Resources
  {
    id: 120,
    name: "lucide",
    full_name: "lucide-icons/lucide",
    description: "Beautiful & consistent icon toolkit made by the community.",
    html_url: "https://github.com/lucide-icons/lucide",
    stargazers_count: 12500,
    language: "TypeScript",
    topics: ["icons", "svg", "design-resources", "icon-pack"],
    owner: {
      login: "lucide-icons",
      avatar_url: "https://avatars.githubusercontent.com/u/66879934",
    },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 121,
    name: "heroicons",
    full_name: "tailwindlabs/heroicons",
    description: "A set of free MIT-licensed high-quality SVG icons.",
    html_url: "https://github.com/tailwindlabs/heroicons",
    stargazers_count: 22000,
    language: "JavaScript",
    topics: ["icons", "svg", "tailwindcss", "design-resources"],
    owner: {
      login: "tailwindlabs",
      avatar_url: "https://avatars.githubusercontent.com/u/67109815",
    },
    updated_at: "2024-11-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Testing & Quality
  {
    id: 130,
    name: "playwright",
    full_name: "microsoft/playwright",
    description: "Playwright is a framework for Web Testing and Automation.",
    html_url: "https://github.com/microsoft/playwright",
    stargazers_count: 69000,
    language: "TypeScript",
    topics: ["testing", "e2e-testing", "automation", "browser"],
    owner: { login: "microsoft", avatar_url: "https://avatars.githubusercontent.com/u/6154722" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
  {
    id: 131,
    name: "vitest",
    full_name: "vitest-dev/vitest",
    description: "Next generation testing framework powered by Vite.",
    html_url: "https://github.com/vitest-dev/vitest",
    stargazers_count: 14500,
    language: "TypeScript",
    topics: ["testing", "unit-testing", "vite", "test"],
    owner: { login: "vitest-dev", avatar_url: "https://avatars.githubusercontent.com/u/95747107" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Productivity
  {
    id: 140,
    name: "obsidian-dataview",
    full_name: "blacksmithgu/obsidian-dataview",
    description: "A data index and query language over Markdown files for Obsidian.",
    html_url: "https://github.com/blacksmithgu/obsidian-dataview",
    stargazers_count: 7200,
    language: "TypeScript",
    topics: ["obsidian-plugin", "productivity", "note-taking", "obsidian"],
    owner: { login: "blacksmithgu", avatar_url: "https://avatars.githubusercontent.com/u/3124702" },
    updated_at: "2024-10-15T00:00:00Z",
    fork: false,
    private: false,
  },

  // Presentations
  {
    id: 150,
    name: "slidev",
    full_name: "slidevjs/slidev",
    description: "Presentation Slides for Developers",
    html_url: "https://github.com/slidevjs/slidev",
    stargazers_count: 34500,
    language: "TypeScript",
    topics: ["presentation", "slides", "markdown", "vue"],
    owner: { login: "slidevjs", avatar_url: "https://avatars.githubusercontent.com/u/80658750" },
    updated_at: "2024-11-20T00:00:00Z",
    fork: false,
    private: false,
  },

  // Mobile
  {
    id: 160,
    name: "expo",
    full_name: "expo/expo",
    description: "An open-source framework for making universal native apps.",
    html_url: "https://github.com/expo/expo",
    stargazers_count: 35500,
    language: "TypeScript",
    topics: ["react-native", "mobile", "ios", "android", "expo"],
    owner: { login: "expo", avatar_url: "https://avatars.githubusercontent.com/u/12504344" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },

  // Infrastructure & DevOps
  {
    id: 170,
    name: "coolify",
    full_name: "coollabsio/coolify",
    description: "An open-source & self-hostable Heroku / Netlify / Vercel alternative.",
    html_url: "https://github.com/coollabsio/coolify",
    stargazers_count: 35000,
    language: "PHP",
    topics: ["devops", "self-hosted", "deployment", "docker", "kubernetes"],
    owner: { login: "coollabsio", avatar_url: "https://avatars.githubusercontent.com/u/71524215" },
    updated_at: "2024-12-01T00:00:00Z",
    fork: false,
    private: false,
  },
];
